---
#test
- name: Configure important user consistently
  hosts: "localhost"
  tasks:
    - name: newbie exists with UID 4000
      user:
        name: newbie
        uid: 4000
        state: present

    - name: Indicate Dry Run Mode
      debug:
        msg: "This is a dry run. No changes will be made."
      when: ansible_check_mode       
