---
- name: test error ingnore
  hosts: "area51-lab"
  tasks:
    - name: error ignore
      yum:
        name: notapkg
        state: latest
      ignore_errors: yes  
    - name: postfix is installed
      yum:
        name: postfix
        state: latest
