---
- name: checking gather facts
  hosts: "area51-lab"
  gather_facts: no
  tasks:
  - name: Prints various Ansible facts
    setup:
    register: output

  - name:   
    debug:
      msg: 
        "The default IPv4 address of {{ output.ansible_fqdn }}"
      
