---
- name: checking gather facts
  hosts: "area51-lab"
  gather_facts: no
  tasks:
  - name: Prints various Ansible facts
    setup:
    debug:
      msg: >
        The default IPv4 address of {{ ansible_fqdn }}
        is {{ ansible_default_ipv4.address }}
