---
- name: checking gather facts
  hosts: "area51-lab"
  gather_facts: no
  tasks:
  - name: Prints various Ansible facts
    setup:
    register: output

  - name:   
    debug:
      vars: >
        The default IPv4 address of {{ ansible_fqdn.output }}
        is {{ ansible_default_ipv4.address.output }}
