---
- name: test handler
  hosts: "area51-lab"
  tasks:
    - name: copy demo.example.conf configuration template
      copy:
        src: /root/python311-env-n/lib/python3.11/Project/lab-test/ping.yml
        dest: /root/python311-env-n/lib/python3.11/Project/lab-test/ping2.yml
      notify:
        - restart_apache
  handlers:
    - name: restart_apache2
      service:
        name: httpd
        state: restarted
