---
- name: Install, start, and enable services
  hosts: "area51-lab"
  tasks:
  - name: Includes the tasks file and defines the variables
    include_vars: 
      file: vars.yml
  - name: Debugs the included tasks
    debug:
      msg: 
        "Age hai: {{ name }}" 
