---
- name: Install, start, and enable services
  hosts: "area51-lab"
  tasks:
  - name: Includes the tasks file and defines the variables
    include_vars: vars.yml
  - name: Debugs the included tasks
    debug:
      msg: >
        "{{ Employee name is "name" and Age is "years" }}
