---
- name: Install, start, and enable services
  hosts: "area51-lab"
  tasks:
  - name: Includes the tasks file and defines the variables
    include: includetasktest.yml
    register: output
  - name: Debugs the included tasks
    debug:
      var: output
