---
- name: tag testing
  hosts: all
  tasks:
    - name: httpd is installed
      yum:
        name: httpd
        state: latest
      tags: webserver
    - name: postfix is installed
      yum:
        name: postfix
        state: latest
