---
- name: test the with item tasks. 
  hosts: "area51-lab"
  tasks:
    - name: Postfix and Dovecot are running
      service:
        name: "{{ item }}"
        state: started
      with_items:
        - postfix
        - dovecot
